import React, { createContext, useContext, useState } from 'react';

export type Language = 'RU' | 'KZ' | 'EN';

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  RU: {
    title: 'Energen — ваш цифровой помощник',
    voiceMode: 'Голосовой режим',
    textChat: 'Текстовый чат',
    findRoom: 'Найти аудиторию',
    findRoomDesc: 'Поиск по номеру или кафедре',
    employees: 'Сотрудники',
    employeesDesc: 'Преподаватели и персонал',
    administration: 'АУП',
    administrationDesc: 'Администрация университета',
    events: 'Мероприятия',
    eventsDesc: 'Конференции, олимпиады, события',
    clubs: 'Клубы',
    clubsDesc: 'Студенческие организации',
    programs: 'Программы',
    programsDesc: 'Образовательные направления',
    payments: 'Оплата',
    paymentsDesc: 'Реквизиты и QR-коды',
    directions: 'Как добраться',
    directionsDesc: 'Маршрут, транспорт, карта',
    askQuestion: 'Задайте вопрос...',
    send: 'Отправить',
    listening: 'Слушаю...',
    thinking: 'Думаю...',
    tapToSpeak: 'Нажмите, чтобы говорить',
    exitVoice: 'Выйти',
    showRoute: 'Показать маршрут',
    bookAppointment: 'Записаться на приём',
    howToGetThere: 'Как добраться',
    joinClub: 'Вступить в клуб',
    register: 'Зарегистрироваться',
    addToCalendar: 'Добавить в календарь',
    downloadQR: 'Скачать QR',
    copyDetails: 'Скопировать реквизиты',
    openInMaps: 'Открыть в картах',
    submitRequest: 'Отправить заявку',
    available: 'Свободно',
    busy: 'Занято',
    home: 'Главная',
    chat: 'Чат',
    back: 'Назад',
  },
  KZ: {
    title: 'Energen — сіздің цифрлық көмекшіңіз',
    voiceMode: 'Дауыстық режим',
    textChat: 'Мәтіндік чат',
    findRoom: 'Аудитория табу',
    findRoomDesc: 'Нөмір немесе кафедра бойынша іздеу',
    employees: 'Қызметкерлер',
    employeesDesc: 'Оқытушылар мен персонал',
    administration: 'ӘУП',
    administrationDesc: 'Университет әкімшілігі',
    events: 'Іс-шаралар',
    eventsDesc: 'Конференциялар, олимпиадалар',
    clubs: 'Клубтар',
    clubsDesc: 'Студенттік ұйымдар',
    programs: 'Бағдарламалар',
    programsDesc: 'Білім беру бағыттары',
    payments: 'Төлем',
    paymentsDesc: 'Деректемелер және QR-кодтар',
    directions: 'Қалай жету',
    directionsDesc: 'Маршрут, көлік, карта',
    askQuestion: 'Сұрақ қойыңыз...',
    send: 'Жіберу',
    listening: 'Тыңдаудамын...',
    thinking: 'Ойлаудамын...',
    tapToSpeak: 'Сөйлеу үшін басыңыз',
    exitVoice: 'Шығу',
    showRoute: 'Маршрут көрсету',
    bookAppointment: 'Қабылдауға жазылу',
    howToGetThere: 'Қалай жету',
    joinClub: 'Клубқа кіру',
    register: 'Тіркелу',
    addToCalendar: 'Күнтізбеге қосу',
    downloadQR: 'QR жүктеу',
    copyDetails: 'Деректемелерді көшіру',
    openInMaps: 'Картада ашу',
    submitRequest: 'Өтінімді жіберу',
    available: 'Бос',
    busy: 'Бос емес',
    home: 'Басты бет',
    chat: 'Чат',
    back: 'Артқа',
  },
  EN: {
    title: 'Energen — your digital assistant',
    voiceMode: 'Voice Mode',
    textChat: 'Text Chat',
    findRoom: 'Find Room',
    findRoomDesc: 'Search by number or department',
    employees: 'Employees',
    employeesDesc: 'Faculty and staff',
    administration: 'Administration',
    administrationDesc: 'University management',
    events: 'Events',
    eventsDesc: 'Conferences, olympiads, events',
    clubs: 'Clubs',
    clubsDesc: 'Student organizations',
    programs: 'Programs',
    programsDesc: 'Educational directions',
    payments: 'Payments',
    paymentsDesc: 'Details and QR codes',
    directions: 'Directions',
    directionsDesc: 'Route, transport, map',
    askQuestion: 'Ask a question...',
    send: 'Send',
    listening: 'Listening...',
    thinking: 'Thinking...',
    tapToSpeak: 'Tap to speak',
    exitVoice: 'Exit',
    showRoute: 'Show route',
    bookAppointment: 'Book appointment',
    howToGetThere: 'How to get there',
    joinClub: 'Join club',
    register: 'Register',
    addToCalendar: 'Add to calendar',
    downloadQR: 'Download QR',
    copyDetails: 'Copy details',
    openInMaps: 'Open in maps',
    submitRequest: 'Submit request',
    available: 'Available',
    busy: 'Busy',
    home: 'Home',
    chat: 'Chat',
    back: 'Back',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'RU',
  setLang: () => {},
  t: (k) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>('RU');
  const t = (key: string) => translations[lang][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
